[build]
    publish = "_site/"
    command = "jekyll build"

[context.deploy-preview]
    environment = { JEKYLL_ENV = "staging" }

[context.branch-deploy]
    environment = { JEKYLL_ENV = "staging" }

[context.production]
    environment = { JEKYLL_ENV = "production" }

[[redirects]]
    from = "https://chihacknight-website.netlify.com/*"
    to = "https://chihacknight.org/:splat"
    status = 301

[[redirects]]
    from = "https://www.chihacknight.org/*"
    to = "https://chihacknight.org/:splat"
    status = 301
