backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  site_domain: chihacknight.netlify.com

media_folder: "images/uploads" # Media files will be stored in the repo under images/uploads


collections:
  - name: "events" # Used in routes, e.g. /admin/collections/blog
    label: "Events" # Used in the UI
    folder: "_posts/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "layout" , name: "layout" , widget: "hidden", default: "event"}
      - {label: "Categories", name: "categories", widget: "hidden", default: "events"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Categories", name: "catagories", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Author Url", name: "author_url", widget: "string"}
      - {label: "Author Image", name: "author_image", widget: "image"}
      - {label: "Author Bio", name: "author_bio", widget: "text"}
      - {label: "Published", name: "published", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "projects" # Used in routes, e.g. /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "_posts/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
